[workspace]
members = ["server", "grind"]
resolver = "3"

[workspace.package]
version = "2.8.0"
edition = "2024"

[workspace.dependencies]
axum = "=0.8.9"
base64 = "=0.22.1"
bytes = "=1.11.1"
chrono = { version = "=0.4.45", default-features = false }
clap = "=4.6.1"
flate2 = "=1.1.9"
hex = "=0.4.3"
hmac = "=0.13.0"
http = "=1.4.2"
ignore = "=0.4.26"
prost = "=0.14.4"
prost-types = "=0.14.4"
rand = "=0.10.1"
reqwest = { version = "=0.13.4", default-features = false }
roxmltree = "=0.21.1"
rusqlite = "=0.40.1"
semver = "=1.0.28"
serde = "=1.0.228"
serde_json = "=1.0.150"
sha1 = "=0.11.0"
sha2 = "=0.11.0"
tempfile = "=3.27.0"
tar = "=0.4.46"
thiserror = "=2.0.18"
tokio = "=1.52.3"
tokio-stream = "=0.1.18"
toml = "=1.1.2"
tonic = { version = "=0.14.6", default-features = false }
tonic-prost = "=0.14.6"
tonic-prost-build = "=0.14.6"
tonic-web = "=0.14.6"
tower = "=0.5.3"
tower-http = "=0.7.0"
url = "=2.5.8"
urlencoding = "=2.1.3"
