[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "thonny-codegrinder-plugin"
version = "2.7.3"
description = "Thonny plugin to integrate with CodeGrinder for coding practice"
readme = { text = """Thonny plugin to integrate with CodeGrinder.
This is for students enrolled in Python programming classes
that use CodeGrinder for automatic testing and grading.""", content-type = "text/plain" }
requires-python = ">=3.10"
license = { text = "AGPL-3.0-or-later" }
authors = [
  { name = "Russ Ross", email = "russ@russross.com" }
]
keywords = ["Thonny", "CodeGrinder", "education"]
classifiers = [
  "Intended Audience :: Education",
  "Intended Audience :: End Users/Desktop",
  "License :: OSI Approved :: GNU Affero General Public License v3",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
  "Topic :: Education",
]

dependencies = [
  "certifi>=2022.12.7",
  "dataclasses-json>=0.5.7",
  "Pillow>=9.0.0",
  "requests>=2.28.0",
  "thonny>=3.3.0",
  "websocket-client>=1.4.0",
]

[project.urls]
Homepage = "https://github.com/russross/codegrinder/"

[tool.setuptools]
packages = [
  "thonnycontrib.thonny_codegrinder_plugin",
  "thonnycontrib.thonny_codegrinder_plugin.tkhtmlview",
]
