#!/bin/sh
set -eu

CODEGRINDEROOT="/home/russ/codegrinder"

/usr/bin/certbot renew \
  --quiet \
  --standalone \
  --preferred-challenges http \
  --deploy-hook "rc-service nginx reload" \
  --config-dir "${CODEGRINDEROOT}/certs/letsencrypt" \
  --work-dir "${CODEGRINDEROOT}/certs/letsencrypt-work" \
  --logs-dir "${CODEGRINDEROOT}/certs/letsencrypt-logs"
