// @generated by protobuf-ts 2.11.1 with parameter long_type_string,generate_dependencies,client_generic
// @generated from protobuf file "codegrinder.proto" (package "codegrinder", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { CodeGrinderService } from "./codegrinder";
import type { DaycareResponse } from "./codegrinder";
import type { DaycareRequest } from "./codegrinder";
import type { ServerStreamingCall } from "@protobuf-ts/runtime-rpc";
import type { PostCommitBundlesSignedResponse } from "./codegrinder";
import type { PostCommitBundlesSignedRequest } from "./codegrinder";
import type { PostCommitBundlesUnsignedResponse } from "./codegrinder";
import type { PostCommitBundlesUnsignedRequest } from "./codegrinder";
import type { PutProblemSetBundleResponse } from "./codegrinder";
import type { PutProblemSetBundleRequest } from "./codegrinder";
import type { PostProblemSetBundleResponse } from "./codegrinder";
import type { PostProblemSetBundleRequest } from "./codegrinder";
import type { PutProblemBundleResponse } from "./codegrinder";
import type { PutProblemBundleRequest } from "./codegrinder";
import type { PostProblemBundleConfirmedResponse } from "./codegrinder";
import type { PostProblemBundleConfirmedRequest } from "./codegrinder";
import type { PostProblemBundleUnconfirmedResponse } from "./codegrinder";
import type { PostProblemBundleUnconfirmedRequest } from "./codegrinder";
import type { GetAssignmentProblemStepCommitLastResponse } from "./codegrinder";
import type { GetAssignmentProblemStepCommitLastRequest } from "./codegrinder";
import type { GetAssignmentProblemCommitLastResponse } from "./codegrinder";
import type { GetAssignmentProblemCommitLastRequest } from "./codegrinder";
import type { GetAssignmentResponse } from "./codegrinder";
import type { GetAssignmentRequest } from "./codegrinder";
import type { GetAssignmentsResponse } from "./codegrinder";
import type { GetAssignmentsRequest } from "./codegrinder";
import type { GetCourseUserAssignmentsResponse } from "./codegrinder";
import type { GetCourseUserAssignmentsRequest } from "./codegrinder";
import type { GetUserAssignmentsResponse } from "./codegrinder";
import type { GetUserAssignmentsRequest } from "./codegrinder";
import type { GetCourseUsersResponse } from "./codegrinder";
import type { GetCourseUsersRequest } from "./codegrinder";
import type { GetUserResponse } from "./codegrinder";
import type { GetUserRequest } from "./codegrinder";
import type { GetUserMeResponse } from "./codegrinder";
import type { GetUserMeRequest } from "./codegrinder";
import type { GetUsersResponse } from "./codegrinder";
import type { GetUsersRequest } from "./codegrinder";
import type { GetCourseResponse } from "./codegrinder";
import type { GetCourseRequest } from "./codegrinder";
import type { GetCoursesResponse } from "./codegrinder";
import type { GetCoursesRequest } from "./codegrinder";
import type { GetProblemSetProblemsResponse } from "./codegrinder";
import type { GetProblemSetProblemsRequest } from "./codegrinder";
import type { GetProblemSetResponse } from "./codegrinder";
import type { GetProblemSetRequest } from "./codegrinder";
import type { GetProblemSetsResponse } from "./codegrinder";
import type { GetProblemSetsRequest } from "./codegrinder";
import type { GetProblemStepResponse } from "./codegrinder";
import type { GetProblemStepRequest } from "./codegrinder";
import type { GetProblemStepsResponse } from "./codegrinder";
import type { GetProblemStepsRequest } from "./codegrinder";
import type { GetProblemResponse } from "./codegrinder";
import type { GetProblemRequest } from "./codegrinder";
import type { GetProblemsResponse } from "./codegrinder";
import type { GetProblemsRequest } from "./codegrinder";
import type { GetProblemTypeResponse } from "./codegrinder";
import type { GetProblemTypeRequest } from "./codegrinder";
import type { GetProblemTypesResponse } from "./codegrinder";
import type { GetProblemTypesRequest } from "./codegrinder";
import type { GetVersionResponse } from "./codegrinder";
import type { GetVersionRequest } from "./codegrinder";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { ListProblemsResponse } from "./codegrinder";
import type { ListProblemsRequest } from "./codegrinder";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * CodeGrinderService provides CodeGrinder operations
 *
 * @generated from protobuf service codegrinder.CodeGrinderService
 */
export interface ICodeGrinderServiceClient {
    /**
     * ListProblems retrieves all problems and related data for the authenticated user
     *
     * @generated from protobuf rpc: ListProblems
     */
    listProblems(input: ListProblemsRequest, options?: RpcOptions): UnaryCall<ListProblemsRequest, ListProblemsResponse>;
    /**
     * GetVersion retrieves version information
     *
     * @generated from protobuf rpc: GetVersion
     */
    getVersion(input: GetVersionRequest, options?: RpcOptions): UnaryCall<GetVersionRequest, GetVersionResponse>;
    /**
     * GetProblemTypes retrieves all problem types
     *
     * @generated from protobuf rpc: GetProblemTypes
     */
    getProblemTypes(input: GetProblemTypesRequest, options?: RpcOptions): UnaryCall<GetProblemTypesRequest, GetProblemTypesResponse>;
    /**
     * GetProblemType retrieves a specific problem type
     *
     * @generated from protobuf rpc: GetProblemType
     */
    getProblemType(input: GetProblemTypeRequest, options?: RpcOptions): UnaryCall<GetProblemTypeRequest, GetProblemTypeResponse>;
    /**
     * GetProblems retrieves problems with optional filters
     *
     * @generated from protobuf rpc: GetProblems
     */
    getProblems(input: GetProblemsRequest, options?: RpcOptions): UnaryCall<GetProblemsRequest, GetProblemsResponse>;
    /**
     * GetProblem retrieves a specific problem
     *
     * @generated from protobuf rpc: GetProblem
     */
    getProblem(input: GetProblemRequest, options?: RpcOptions): UnaryCall<GetProblemRequest, GetProblemResponse>;
    /**
     * GetProblemSteps retrieves steps for a problem
     *
     * @generated from protobuf rpc: GetProblemSteps
     */
    getProblemSteps(input: GetProblemStepsRequest, options?: RpcOptions): UnaryCall<GetProblemStepsRequest, GetProblemStepsResponse>;
    /**
     * GetProblemStep retrieves a specific step
     *
     * @generated from protobuf rpc: GetProblemStep
     */
    getProblemStep(input: GetProblemStepRequest, options?: RpcOptions): UnaryCall<GetProblemStepRequest, GetProblemStepResponse>;
    /**
     * GetProblemSets retrieves problem sets with optional filters
     *
     * @generated from protobuf rpc: GetProblemSets
     */
    getProblemSets(input: GetProblemSetsRequest, options?: RpcOptions): UnaryCall<GetProblemSetsRequest, GetProblemSetsResponse>;
    /**
     * GetProblemSet retrieves a specific problem set
     *
     * @generated from protobuf rpc: GetProblemSet
     */
    getProblemSet(input: GetProblemSetRequest, options?: RpcOptions): UnaryCall<GetProblemSetRequest, GetProblemSetResponse>;
    /**
     * GetProblemSetProblems retrieves problems in a problem set
     *
     * @generated from protobuf rpc: GetProblemSetProblems
     */
    getProblemSetProblems(input: GetProblemSetProblemsRequest, options?: RpcOptions): UnaryCall<GetProblemSetProblemsRequest, GetProblemSetProblemsResponse>;
    /**
     * GetCourses retrieves courses with optional filters
     *
     * @generated from protobuf rpc: GetCourses
     */
    getCourses(input: GetCoursesRequest, options?: RpcOptions): UnaryCall<GetCoursesRequest, GetCoursesResponse>;
    /**
     * GetCourse retrieves a specific course
     *
     * @generated from protobuf rpc: GetCourse
     */
    getCourse(input: GetCourseRequest, options?: RpcOptions): UnaryCall<GetCourseRequest, GetCourseResponse>;
    /**
     * GetUsers retrieves users with optional filters
     *
     * @generated from protobuf rpc: GetUsers
     */
    getUsers(input: GetUsersRequest, options?: RpcOptions): UnaryCall<GetUsersRequest, GetUsersResponse>;
    /**
     * GetUserMe retrieves the current user
     *
     * @generated from protobuf rpc: GetUserMe
     */
    getUserMe(input: GetUserMeRequest, options?: RpcOptions): UnaryCall<GetUserMeRequest, GetUserMeResponse>;
    /**
     * GetUser retrieves a specific user
     *
     * @generated from protobuf rpc: GetUser
     */
    getUser(input: GetUserRequest, options?: RpcOptions): UnaryCall<GetUserRequest, GetUserResponse>;
    /**
     * GetCourseUsers retrieves users in a course
     *
     * @generated from protobuf rpc: GetCourseUsers
     */
    getCourseUsers(input: GetCourseUsersRequest, options?: RpcOptions): UnaryCall<GetCourseUsersRequest, GetCourseUsersResponse>;
    /**
     * GetUserAssignments retrieves assignments for a user
     *
     * @generated from protobuf rpc: GetUserAssignments
     */
    getUserAssignments(input: GetUserAssignmentsRequest, options?: RpcOptions): UnaryCall<GetUserAssignmentsRequest, GetUserAssignmentsResponse>;
    /**
     * GetCourseUserAssignments retrieves assignments for a user in a course
     *
     * @generated from protobuf rpc: GetCourseUserAssignments
     */
    getCourseUserAssignments(input: GetCourseUserAssignmentsRequest, options?: RpcOptions): UnaryCall<GetCourseUserAssignmentsRequest, GetCourseUserAssignmentsResponse>;
    /**
     * GetAssignments retrieves assignments with optional filters
     *
     * @generated from protobuf rpc: GetAssignments
     */
    getAssignments(input: GetAssignmentsRequest, options?: RpcOptions): UnaryCall<GetAssignmentsRequest, GetAssignmentsResponse>;
    /**
     * GetAssignment retrieves a specific assignment
     *
     * @generated from protobuf rpc: GetAssignment
     */
    getAssignment(input: GetAssignmentRequest, options?: RpcOptions): UnaryCall<GetAssignmentRequest, GetAssignmentResponse>;
    /**
     * GetAssignmentProblemCommitLast retrieves the last commit for a problem in an assignment
     *
     * @generated from protobuf rpc: GetAssignmentProblemCommitLast
     */
    getAssignmentProblemCommitLast(input: GetAssignmentProblemCommitLastRequest, options?: RpcOptions): UnaryCall<GetAssignmentProblemCommitLastRequest, GetAssignmentProblemCommitLastResponse>;
    /**
     * GetAssignmentProblemStepCommitLast retrieves the last commit for a step in an assignment
     *
     * @generated from protobuf rpc: GetAssignmentProblemStepCommitLast
     */
    getAssignmentProblemStepCommitLast(input: GetAssignmentProblemStepCommitLastRequest, options?: RpcOptions): UnaryCall<GetAssignmentProblemStepCommitLastRequest, GetAssignmentProblemStepCommitLastResponse>;
    /**
     * PostProblemBundleUnconfirmed handles unconfirmed problem bundle
     *
     * @generated from protobuf rpc: PostProblemBundleUnconfirmed
     */
    postProblemBundleUnconfirmed(input: PostProblemBundleUnconfirmedRequest, options?: RpcOptions): UnaryCall<PostProblemBundleUnconfirmedRequest, PostProblemBundleUnconfirmedResponse>;
    /**
     * PostProblemBundleConfirmed handles confirmed problem bundle
     *
     * @generated from protobuf rpc: PostProblemBundleConfirmed
     */
    postProblemBundleConfirmed(input: PostProblemBundleConfirmedRequest, options?: RpcOptions): UnaryCall<PostProblemBundleConfirmedRequest, PostProblemBundleConfirmedResponse>;
    /**
     * PutProblemBundle handles updating problem bundle
     *
     * @generated from protobuf rpc: PutProblemBundle
     */
    putProblemBundle(input: PutProblemBundleRequest, options?: RpcOptions): UnaryCall<PutProblemBundleRequest, PutProblemBundleResponse>;
    /**
     * PostProblemSetBundle handles problem set bundle
     *
     * @generated from protobuf rpc: PostProblemSetBundle
     */
    postProblemSetBundle(input: PostProblemSetBundleRequest, options?: RpcOptions): UnaryCall<PostProblemSetBundleRequest, PostProblemSetBundleResponse>;
    /**
     * PutProblemSetBundle handles updating problem set bundle
     *
     * @generated from protobuf rpc: PutProblemSetBundle
     */
    putProblemSetBundle(input: PutProblemSetBundleRequest, options?: RpcOptions): UnaryCall<PutProblemSetBundleRequest, PutProblemSetBundleResponse>;
    /**
     * PostCommitBundlesUnsigned handles unsigned commit bundle
     *
     * @generated from protobuf rpc: PostCommitBundlesUnsigned
     */
    postCommitBundlesUnsigned(input: PostCommitBundlesUnsignedRequest, options?: RpcOptions): UnaryCall<PostCommitBundlesUnsignedRequest, PostCommitBundlesUnsignedResponse>;
    /**
     * PostCommitBundlesSigned handles signed commit bundle
     *
     * @generated from protobuf rpc: PostCommitBundlesSigned
     */
    postCommitBundlesSigned(input: PostCommitBundlesSignedRequest, options?: RpcOptions): UnaryCall<PostCommitBundlesSignedRequest, PostCommitBundlesSignedResponse>;
    /**
     * Daycare handles streaming daycare requests
     *
     * @generated from protobuf rpc: Daycare
     */
    daycare(input: DaycareRequest, options?: RpcOptions): ServerStreamingCall<DaycareRequest, DaycareResponse>;
}
/**
 * CodeGrinderService provides CodeGrinder operations
 *
 * @generated from protobuf service codegrinder.CodeGrinderService
 */
export class CodeGrinderServiceClient implements ICodeGrinderServiceClient, ServiceInfo {
    typeName = CodeGrinderService.typeName;
    methods = CodeGrinderService.methods;
    options = CodeGrinderService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * ListProblems retrieves all problems and related data for the authenticated user
     *
     * @generated from protobuf rpc: ListProblems
     */
    listProblems(input: ListProblemsRequest, options?: RpcOptions): UnaryCall<ListProblemsRequest, ListProblemsResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListProblemsRequest, ListProblemsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * GetVersion retrieves version information
     *
     * @generated from protobuf rpc: GetVersion
     */
    getVersion(input: GetVersionRequest, options?: RpcOptions): UnaryCall<GetVersionRequest, GetVersionResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetVersionRequest, GetVersionResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * GetProblemTypes retrieves all problem types
     *
     * @generated from protobuf rpc: GetProblemTypes
     */
    getProblemTypes(input: GetProblemTypesRequest, options?: RpcOptions): UnaryCall<GetProblemTypesRequest, GetProblemTypesResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetProblemTypesRequest, GetProblemTypesResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * GetProblemType retrieves a specific problem type
     *
     * @generated from protobuf rpc: GetProblemType
     */
    getProblemType(input: GetProblemTypeRequest, options?: RpcOptions): UnaryCall<GetProblemTypeRequest, GetProblemTypeResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetProblemTypeRequest, GetProblemTypeResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * GetProblems retrieves problems with optional filters
     *
     * @generated from protobuf rpc: GetProblems
     */
    getProblems(input: GetProblemsRequest, options?: RpcOptions): UnaryCall<GetProblemsRequest, GetProblemsResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetProblemsRequest, GetProblemsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * GetProblem retrieves a specific problem
     *
     * @generated from protobuf rpc: GetProblem
     */
    getProblem(input: GetProblemRequest, options?: RpcOptions): UnaryCall<GetProblemRequest, GetProblemResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetProblemRequest, GetProblemResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * GetProblemSteps retrieves steps for a problem
     *
     * @generated from protobuf rpc: GetProblemSteps
     */
    getProblemSteps(input: GetProblemStepsRequest, options?: RpcOptions): UnaryCall<GetProblemStepsRequest, GetProblemStepsResponse> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetProblemStepsRequest, GetProblemStepsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * GetProblemStep retrieves a specific step
     *
     * @generated from protobuf rpc: GetProblemStep
     */
    getProblemStep(input: GetProblemStepRequest, options?: RpcOptions): UnaryCall<GetProblemStepRequest, GetProblemStepResponse> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetProblemStepRequest, GetProblemStepResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * GetProblemSets retrieves problem sets with optional filters
     *
     * @generated from protobuf rpc: GetProblemSets
     */
    getProblemSets(input: GetProblemSetsRequest, options?: RpcOptions): UnaryCall<GetProblemSetsRequest, GetProblemSetsResponse> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetProblemSetsRequest, GetProblemSetsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * GetProblemSet retrieves a specific problem set
     *
     * @generated from protobuf rpc: GetProblemSet
     */
    getProblemSet(input: GetProblemSetRequest, options?: RpcOptions): UnaryCall<GetProblemSetRequest, GetProblemSetResponse> {
        const method = this.methods[9], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetProblemSetRequest, GetProblemSetResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * GetProblemSetProblems retrieves problems in a problem set
     *
     * @generated from protobuf rpc: GetProblemSetProblems
     */
    getProblemSetProblems(input: GetProblemSetProblemsRequest, options?: RpcOptions): UnaryCall<GetProblemSetProblemsRequest, GetProblemSetProblemsResponse> {
        const method = this.methods[10], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetProblemSetProblemsRequest, GetProblemSetProblemsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * GetCourses retrieves courses with optional filters
     *
     * @generated from protobuf rpc: GetCourses
     */
    getCourses(input: GetCoursesRequest, options?: RpcOptions): UnaryCall<GetCoursesRequest, GetCoursesResponse> {
        const method = this.methods[11], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetCoursesRequest, GetCoursesResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * GetCourse retrieves a specific course
     *
     * @generated from protobuf rpc: GetCourse
     */
    getCourse(input: GetCourseRequest, options?: RpcOptions): UnaryCall<GetCourseRequest, GetCourseResponse> {
        const method = this.methods[12], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetCourseRequest, GetCourseResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * GetUsers retrieves users with optional filters
     *
     * @generated from protobuf rpc: GetUsers
     */
    getUsers(input: GetUsersRequest, options?: RpcOptions): UnaryCall<GetUsersRequest, GetUsersResponse> {
        const method = this.methods[13], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetUsersRequest, GetUsersResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * GetUserMe retrieves the current user
     *
     * @generated from protobuf rpc: GetUserMe
     */
    getUserMe(input: GetUserMeRequest, options?: RpcOptions): UnaryCall<GetUserMeRequest, GetUserMeResponse> {
        const method = this.methods[14], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetUserMeRequest, GetUserMeResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * GetUser retrieves a specific user
     *
     * @generated from protobuf rpc: GetUser
     */
    getUser(input: GetUserRequest, options?: RpcOptions): UnaryCall<GetUserRequest, GetUserResponse> {
        const method = this.methods[15], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetUserRequest, GetUserResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * GetCourseUsers retrieves users in a course
     *
     * @generated from protobuf rpc: GetCourseUsers
     */
    getCourseUsers(input: GetCourseUsersRequest, options?: RpcOptions): UnaryCall<GetCourseUsersRequest, GetCourseUsersResponse> {
        const method = this.methods[16], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetCourseUsersRequest, GetCourseUsersResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * GetUserAssignments retrieves assignments for a user
     *
     * @generated from protobuf rpc: GetUserAssignments
     */
    getUserAssignments(input: GetUserAssignmentsRequest, options?: RpcOptions): UnaryCall<GetUserAssignmentsRequest, GetUserAssignmentsResponse> {
        const method = this.methods[17], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetUserAssignmentsRequest, GetUserAssignmentsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * GetCourseUserAssignments retrieves assignments for a user in a course
     *
     * @generated from protobuf rpc: GetCourseUserAssignments
     */
    getCourseUserAssignments(input: GetCourseUserAssignmentsRequest, options?: RpcOptions): UnaryCall<GetCourseUserAssignmentsRequest, GetCourseUserAssignmentsResponse> {
        const method = this.methods[18], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetCourseUserAssignmentsRequest, GetCourseUserAssignmentsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * GetAssignments retrieves assignments with optional filters
     *
     * @generated from protobuf rpc: GetAssignments
     */
    getAssignments(input: GetAssignmentsRequest, options?: RpcOptions): UnaryCall<GetAssignmentsRequest, GetAssignmentsResponse> {
        const method = this.methods[19], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetAssignmentsRequest, GetAssignmentsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * GetAssignment retrieves a specific assignment
     *
     * @generated from protobuf rpc: GetAssignment
     */
    getAssignment(input: GetAssignmentRequest, options?: RpcOptions): UnaryCall<GetAssignmentRequest, GetAssignmentResponse> {
        const method = this.methods[20], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetAssignmentRequest, GetAssignmentResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * GetAssignmentProblemCommitLast retrieves the last commit for a problem in an assignment
     *
     * @generated from protobuf rpc: GetAssignmentProblemCommitLast
     */
    getAssignmentProblemCommitLast(input: GetAssignmentProblemCommitLastRequest, options?: RpcOptions): UnaryCall<GetAssignmentProblemCommitLastRequest, GetAssignmentProblemCommitLastResponse> {
        const method = this.methods[21], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetAssignmentProblemCommitLastRequest, GetAssignmentProblemCommitLastResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * GetAssignmentProblemStepCommitLast retrieves the last commit for a step in an assignment
     *
     * @generated from protobuf rpc: GetAssignmentProblemStepCommitLast
     */
    getAssignmentProblemStepCommitLast(input: GetAssignmentProblemStepCommitLastRequest, options?: RpcOptions): UnaryCall<GetAssignmentProblemStepCommitLastRequest, GetAssignmentProblemStepCommitLastResponse> {
        const method = this.methods[22], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetAssignmentProblemStepCommitLastRequest, GetAssignmentProblemStepCommitLastResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * PostProblemBundleUnconfirmed handles unconfirmed problem bundle
     *
     * @generated from protobuf rpc: PostProblemBundleUnconfirmed
     */
    postProblemBundleUnconfirmed(input: PostProblemBundleUnconfirmedRequest, options?: RpcOptions): UnaryCall<PostProblemBundleUnconfirmedRequest, PostProblemBundleUnconfirmedResponse> {
        const method = this.methods[23], opt = this._transport.mergeOptions(options);
        return stackIntercept<PostProblemBundleUnconfirmedRequest, PostProblemBundleUnconfirmedResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * PostProblemBundleConfirmed handles confirmed problem bundle
     *
     * @generated from protobuf rpc: PostProblemBundleConfirmed
     */
    postProblemBundleConfirmed(input: PostProblemBundleConfirmedRequest, options?: RpcOptions): UnaryCall<PostProblemBundleConfirmedRequest, PostProblemBundleConfirmedResponse> {
        const method = this.methods[24], opt = this._transport.mergeOptions(options);
        return stackIntercept<PostProblemBundleConfirmedRequest, PostProblemBundleConfirmedResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * PutProblemBundle handles updating problem bundle
     *
     * @generated from protobuf rpc: PutProblemBundle
     */
    putProblemBundle(input: PutProblemBundleRequest, options?: RpcOptions): UnaryCall<PutProblemBundleRequest, PutProblemBundleResponse> {
        const method = this.methods[25], opt = this._transport.mergeOptions(options);
        return stackIntercept<PutProblemBundleRequest, PutProblemBundleResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * PostProblemSetBundle handles problem set bundle
     *
     * @generated from protobuf rpc: PostProblemSetBundle
     */
    postProblemSetBundle(input: PostProblemSetBundleRequest, options?: RpcOptions): UnaryCall<PostProblemSetBundleRequest, PostProblemSetBundleResponse> {
        const method = this.methods[26], opt = this._transport.mergeOptions(options);
        return stackIntercept<PostProblemSetBundleRequest, PostProblemSetBundleResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * PutProblemSetBundle handles updating problem set bundle
     *
     * @generated from protobuf rpc: PutProblemSetBundle
     */
    putProblemSetBundle(input: PutProblemSetBundleRequest, options?: RpcOptions): UnaryCall<PutProblemSetBundleRequest, PutProblemSetBundleResponse> {
        const method = this.methods[27], opt = this._transport.mergeOptions(options);
        return stackIntercept<PutProblemSetBundleRequest, PutProblemSetBundleResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * PostCommitBundlesUnsigned handles unsigned commit bundle
     *
     * @generated from protobuf rpc: PostCommitBundlesUnsigned
     */
    postCommitBundlesUnsigned(input: PostCommitBundlesUnsignedRequest, options?: RpcOptions): UnaryCall<PostCommitBundlesUnsignedRequest, PostCommitBundlesUnsignedResponse> {
        const method = this.methods[28], opt = this._transport.mergeOptions(options);
        return stackIntercept<PostCommitBundlesUnsignedRequest, PostCommitBundlesUnsignedResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * PostCommitBundlesSigned handles signed commit bundle
     *
     * @generated from protobuf rpc: PostCommitBundlesSigned
     */
    postCommitBundlesSigned(input: PostCommitBundlesSignedRequest, options?: RpcOptions): UnaryCall<PostCommitBundlesSignedRequest, PostCommitBundlesSignedResponse> {
        const method = this.methods[29], opt = this._transport.mergeOptions(options);
        return stackIntercept<PostCommitBundlesSignedRequest, PostCommitBundlesSignedResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Daycare handles streaming daycare requests
     *
     * @generated from protobuf rpc: Daycare
     */
    daycare(input: DaycareRequest, options?: RpcOptions): ServerStreamingCall<DaycareRequest, DaycareResponse> {
        const method = this.methods[30], opt = this._transport.mergeOptions(options);
        return stackIntercept<DaycareRequest, DaycareResponse>("serverStreaming", this._transport, method, opt, input);
    }
}
