#!/bin/sh

set -e

if [ -z "$CODEGRINDERROOT"]; then
    CODEGRINDERROOT="$HOME"/codegrinder
fi

BACKUPDIR="$HOME"/backup
DAY=`date '+%Y-%m-%d'`
SOURCE="$CODEGRINDERROOT"/db/codegrinder.db
DBFILE=database_$DAY.db

/usr/bin/sqlite3 $SOURCE vacuum
/usr/bin/sqlite3 $SOURCE .backup\ "$BACKUPDIR"/$DBFILE
/usr/bin/xz "$BACKUPDIR"/$DBFILE
