#!/bin/sh

set -e

if [ -z "$CODEGRINDERROOT" ]; then
    CODEGRINDERROOT="$HOME/codegrinder"
fi

BACKUPDIR="$CODEGRINDERROOT/backup"

# make sure all the backup directories exist
mkdir -p "$BACKUPDIR"
mkdir -p "$BACKUPDIR/yearly"
mkdir -p "$BACKUPDIR/monthly"
mkdir -p "$BACKUPDIR/weekly"
mkdir -p "$BACKUPDIR/daily"

SOURCE="$CODEGRINDERROOT/db/codegrinder.db"
DBFILE=codegrinder_`date '+%Y-%m-%d'`.db

#/usr/bin/sqlite3 "$SOURCE" vacuum 2> /dev/null
/usr/bin/sqlite3 "$SOURCE" .backup\ "$BACKUPDIR/$DBFILE" 2> /dev/null
/usr/bin/xz "$BACKUPDIR/$DBFILE"

COMPRESSED="$BACKUPDIR/$DBFILE.xz"

# delete all but the top $1 files from $2 when reverse sorted
keep_top () {
    name_pattern='*.db.xz'
    tailn=`expr $1 + 1`
    rm -f `find $2 -type f -name $name_pattern | sort -r | tail -n +$tailn`
}

# keep a backup at the end of each semester: Dec 31, May 11, Aug 7
DAY=`date '+%m-%d'`
if [ "$DAY" = "12-31" ] || [ "$DAY" = "05-11" ] || [ "$DAY" = "08-07" ]; then
    ln "$COMPRESSED" "$BACKUPDIR/yearly/"
fi

# keep a monthly backup going back 12 months
if [ `date +%-d` -eq 1 ]; then
    ln "$COMPRESSED" "$BACKUPDIR/monthly/"
    keep_top 12 "$BACKUPDIR/monthly/"
fi

# keep a weekly backup going back 10 weeks
if [ `date +%w` -eq 1 ] ; then
    ln "$COMPRESSED" "$BACKUPDIR/weekly/"
    keep_top 10 "$BACKUPDIR/weekly/"
fi

# keep a daily backup going back 10 days
ln "$COMPRESSED" "$BACKUPDIR/daily/"
keep_top 10 "$BACKUPDIR/daily/"

rm "$COMPRESSED"
